# Python多项式处理基础命令
[NumPy](https://numpy.org/) 在[Python](https://www.python.org/) 生态中的地位无需再多言，完全可以说「没有NumPy就没有Python在大数据和机器学习领域的流行」。
在NumPy 1.4前，对多项式的操作使用的包是 [numpy.poly1d](https://numpy.org/doc/stable/reference/generated/numpy.poly1d.html#numpy.poly1d) ； NumPy 1.4 后（当下版本1.23），推荐使用更方便易用的包[numpy.polynomial](https://numpy.org/doc/stable/reference/routines.polynomials.package.html#module-numpy.polynomial)。

引用方法如下：

In [12]:
from numpy.polynomial import Polynomial
p = Polynomial([3, 2, 1])
print(p)
p

3.0 + 2.0·x¹ + 1.0·x²


Polynomial([3., 2., 1.], domain=[-1,  1], window=[-1,  1])

具有下述属性：

In [8]:
# 系数
p.coef

array([3., 2., 1.])

In [9]:
# 定义域 : 默认为[-1,1]
p.domain

array([-1,  1])

In [10]:
# 窗口： 默认为[-1,1]
p.window

array([-1,  1])

## 基本代数算术操作
加/减/乘/乘方

In [13]:
p + p

Polynomial([6., 4., 2.], domain=[-1.,  1.], window=[-1.,  1.])

In [14]:
p - p

Polynomial([0.], domain=[-1.,  1.], window=[-1.,  1.])

In [15]:
p * p

Polynomial([ 9., 12., 10.,  4.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

In [16]:
p ** 2

Polynomial([ 9., 12., 10.,  4.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

除法

In [18]:
p // Polynomial([-1, 1])

Polynomial([3., 1.], domain=[-1.,  1.], window=[-1.,  1.])

In [28]:
p / 2

Polynomial([1.5, 1. , 0.5], domain=[-1.,  1.], window=[-1.,  1.])

余数

In [19]:
p % Polynomial([-1, 1])

Polynomial([6.], domain=[-1.,  1.], window=[-1.,  1.])

带余除法

In [21]:
quo, rem = divmod(p, Polynomial([-1, 1]))
print(quo,rem)

3.0 + 1.0·x¹ 6.0


求值

In [22]:
x = np.arange(5)
p(x)

array([ 3.,  6., 11., 18., 27.])

In [23]:
x = np.arange(6).reshape(3,2)
p(x)

array([[ 3.,  6.],
       [11., 18.],
       [27., 38.]])

代换（将x代换为相应值）

In [24]:
p(p)

Polynomial([18., 16., 12.,  4.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

求根

In [25]:
p.roots()

array([-1.-1.41421356j, -1.+1.41421356j])

直接用list表示多项式

In [26]:
p + [1,2,3]

Polynomial([4., 4., 4.], domain=[-1.,  1.], window=[-1.,  1.])

In [27]:
[1,2,3] * p

Polynomial([ 3.,  8., 14.,  8.,  3.], domain=[-1.,  1.], window=[-1.,  1.])

## 微积分操作
下界-1，积分常数2，二重积分

In [31]:
p.integ(2,lbnd=-1,k=2)

Polynomial([3.08333333, 4.33333333, 1.5       , 0.33333333, 0.08333333], domain=[-1.,  1.], window=[-1.,  1.])

二阶导数

In [32]:
p.deriv(2)

Polynomial([2.], domain=[-1.,  1.], window=[-1.,  1.])

## 其他多项式构造方法
从根构造

In [34]:
p = Polynomial.fromroots([1, 2, 3])
p

Polynomial([-6., 11., -6.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

In [35]:
Polynomial.basis(3)

Polynomial([0., 0., 0., 1.], domain=[-1.,  1.], window=[-1.,  1.])

## 插值

In [37]:
rng = np.random.default_rng()
x = np.arange(10)
y = np.arange(10) + rng.standard_normal(10)

In [41]:
p_fitted = Polynomial.fit(x, y, deg=2)
p_fitted

Polynomial([ 4.49241729,  4.04202433, -0.04876123], domain=[0., 9.], window=[-1.,  1.])

## 参考
- [Using the Convenience Classes](https://numpy.org/doc/stable/reference/routines.polynomials.classes.html)
- [numpy.polynomial package](https://numpy.org/doc/stable/reference/routines.polynomials.package.html#module-numpy.polynomial)